import { Question } from '../types';

export const TEST7_RW_MODULE_2_QUESTIONS: Question[] = [
  {
    id: 1734,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 1,
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    questionText: `Taking photographs in the mid-1800s was complicated and expensive, but this changed with the 1854 invention of the carte de visite, a small photo that cost little to make. Carte de visite photos helped to _______ photography: they made it easy and enjoyable for everyday people to have their pictures taken, and people at the time loved exchanging these small photos with friends and family.\n\nWhich choice completes the text with the most logical and precise word or phrase?`,
    options: [
      { id: 'A', text: 'weaken' },
      { id: 'B', text: 'praise' },
      { id: 'C', text: 'popularize' },
      { id: 'D', text: 'isolate' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because "popularize" means to make something accessible and liked by many people, which matches making photography easy and enjoyable for everyday people.'
  },
  {
    id: 1735,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 2,
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    questionText: `Painter Alma W. Thomas was fascinated by the colors and shapes found in nature. The flowers and trees in the garden at her home in Washington, DC, _______ her work. For example, Thomas’s use of broken brushstrokes was inspired by the way that light would shine through the leaves of a tree in front of her house.\n\nWhich choice completes the text with the most logical and precise word or phrase?`,
    options: [
      { id: 'A', text: 'restricted' },
      { id: 'B', text: 'announced' },
      { id: 'C', text: 'distracted' },
      { id: 'D', text: 'influenced' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because "influenced" means had an effect on or inspired, which directly connects to the example of her brushstrokes being inspired by light through tree leaves.'
  },
  {
    id: 1736,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 3,
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    questionText: `In the 1990s, conservationists began planting more than 500,000 native trees in the habitat of the Azores bullfinch to boost the bird’s numbers. This approach was apparently _______: the Azores bullfinch’s population size increased from as few as 100 birds at the end of the 1980s to around 1,300 in 2023.\n\nWhich choice completes the text with the most logical and precise word or phrase?`,
    options: [
      { id: 'A', text: 'amusing' },
      { id: 'B', text: 'costly' },
      { id: 'C', text: 'successful' },
      { id: 'D', text: 'disastrous' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because "successful" matches the evidence that the bird\'s population increased thirteenfold from 100 to 1,300.'
  },
  {
    id: 1737,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 4,
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    questionText: `The recently observed gamma ray burst GRB 230307A lasted for 200 seconds, _______ for a burst generated by the merger of neutron stars. Bursts caused by neutron mergers typically last fewer than 2 seconds.\n\nWhich choice completes the text with the most logical and precise word or phrase?`,
    options: [
      { id: 'A', text: 'a coincidence' },
      { id: 'B', text: 'a reprieve' },
      { id: 'C', text: 'an incident' },
      { id: 'D', text: 'an oddity' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because "an oddity" means something unusual or anomalous. Lasting 200 seconds when typical mergers last fewer than 2 seconds makes GRB 230307A an anomaly/oddity.'
  },
  {
    id: 1738,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 5,
    domain: 'Craft and Structure',
    skill: 'Words in Context',
    questionText: `In 1776, the United States sent Benjamin Franklin to France to try to win the country’s support in the United States’ fight for independence from Great Britain. Franklin was very popular in France. This _______ surely helped him to convince France to assist the United States.\n\nWhich choice completes the text with the most logical and precise word or phrase?`,
    options: [
      { id: 'A', text: 'thoughtfulness' },
      { id: 'B', text: 'esteem' },
      { id: 'C', text: 'controversy' },
      { id: 'D', text: 'sincerity' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because "esteem" means high regard or favor, which directly refers back to Franklin being "very popular in France."'
  },
  {
    id: 1739,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 6,
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    passageHtml: `<p class="mb-3">In the 1950s, scientists didn’t know much about the ocean floor. <u>Many scientists at the time believed that the ocean floor was mostly flat.</u> But geologist Marie Tharp and her research partner, Bruce Heezen, proved that this idea was wrong. Using sonar data collected from the Atlantic Ocean, Tharp and Heezen showed that the floor was filled with canyons, mountains, and valleys.</p>`,
    questionText: `Which choice best describes the function of the underlined sentence in the text as a whole?`,
    options: [
      { id: 'A', text: 'It identifies a scientific belief that Tharp and Heezen showed to be wrong.' },
      { id: 'B', text: 'It describes the design of Tharp and Heezen’s experiment.' },
      { id: 'C', text: 'It emphasizes a disagreement between Tharp and Heezen.' },
      { id: 'D', text: 'It presents data to support a claim that Tharp and Heezen made.' }
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct because the underlined sentence states the prevailing belief (flat ocean floor) that Tharp and Heezen subsequently disproved using sonar data.'
  },
  {
    id: 1740,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 7,
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    passageHtml: `<p class="mb-3">In the early days of television in the 1940s, many people thought that US television programs would rely on the financial support of ad agencies and commercial sponsors, much like radio did. But advertisers hesitated to jump into a new space, <u>particularly at a time when the manufacturing of new television sets was stalled due to the US’s involvement in World War II.</u> Broadcasters, like the National Broadcasting Company (NBC), needed to persuade advertisers to support their programming despite not knowing whether there would be a robust television audience to begin with.</p>`,
    questionText: `Which choice best describes the function of the underlined phrase in the text as a whole?`,
    options: [
      { id: 'A', text: 'It compares the beginnings of radio programming with the beginnings of television programming in the United States.' },
      { id: 'B', text: 'It identifies a specific reason behind some advertisers’ hesitance to support television.' },
      { id: 'C', text: 'It describes how broadcasters attempted to convince advertisers to support television.' },
      { id: 'D', text: 'It explains why a type of television programming was popular at the time.' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because the stalled manufacturing of television sets during WWII explains why advertisers were hesitant to spend money sponsoring television programs.'
  },
  {
    id: 1741,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 8,
    domain: 'Craft and Structure',
    skill: 'Text Structure and Purpose',
    passageHtml: `<p class="mb-3">The Bayeux Tapestry, from eleventh-century France, depicts 75 scenes over 250 feet of fabric. It was likely produced by workers embroidering in sections and then joining the resulting panels together. It’s plausible that the workshop that produced the tapestry had never produced one so large, and some researchers claim that a close examination of the joins—the places where the panels are stitched together—suggests that the workers developed and refined their joining process over the course of production. <u>For example, the first join the workers completed exhibits a clear misalignment of the borders of the two panels, whereas the later joins are virtually invisible.</u></p>`,
    questionText: `Which choice best describes the function of the underlined sentence in the text as a whole?`,
    options: [
      { id: 'A', text: 'It identifies the people and events depicted in the Bayeux Tapestry.' },
      { id: 'B', text: 'It supports an argument about the workers who produced the Bayeux Tapestry.' },
      { id: 'C', text: 'It compares the Bayeux Tapestry with other tapestries from eleventh-century France.' },
      { id: 'D', text: 'It describes how researchers determined where the Bayeux Tapestry was produced.' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because the contrast between early misaligned joins and later invisible joins provides concrete evidence supporting the researchers\' claim that workers refined their stitching process over time.'
  },
  {
    id: 1742,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 9,
    domain: 'Craft and Structure',
    skill: 'Cross-Text Connections',
    passageHtml: `<p class="mb-2"><b>Text 1</b><br/>Little is known about how plate tectonics—wherein slabs of Earth’s crust move over, under, away from, and against one another—began. <u>Some researchers contend</u> that tectonic movements began around 3 billion years ago, often noting that computer models of Earth’s mantle temperature at the time indicate that the mantle would have been sufficiently molten to enable the plates to move.</p><p class="mb-2"><b>Text 2</b><br/>Ultimately, any plausible claim about the inception of tectonic movement must rest on empirical evidence from the geological record. Researcher Wriju Chowdhury and his team analyzed the geochemistry of zircon crystals to gain insight into the chemical composition of the magma from which the crystals formed and, based on the data, compellingly argue that plate tectonics may have been occurring as early as 4.2 billion years ago.</p>`,
    questionText: `Based on the texts, how would the author of Text 2 most likely respond to what “some researchers contend” as described in Text 1?`,
    options: [
      { id: 'A', text: 'By suggesting that the temperature of Earth’s mantle 3 billion years ago was likely insufficient to allow for the level of tectonic movement predicted by computer models' },
      { id: 'B', text: 'By distinguishing between computer models of Earth’s mantle temperature that reliably predict the onset of plate tectonics and those that do not' },
      { id: 'C', text: 'By indicating that computer models of Earth’s mantle temperature are still being improved such that new models tend to be much more reliable than their predecessors' },
      { id: 'D', text: 'By asserting that a more definitive form of evidence than the computer models suggests a different timeline for the onset of plate tectonics on Earth' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because the author of Text 2 emphasizes that claims must rest on "empirical evidence from the geological record" (zircon geochemistry) and concludes that plate tectonics began much earlier (4.2 billion years ago) than the 3 billion years suggested by computer models.'
  },
  {
    id: 1743,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 10,
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    questionText: `<i>Hevea brasiliensis</i>, a tree in the Amazon rainforest, is the world’s main source of natural rubber. The tree produces a milky substance called latex that is used to make rubber. The bark of <i>Hevea brasiliensis</i> is helpful for the process of making rubber because it has a unique structure that makes it easy to collect latex. A network of tubes in the tree’s inner bark helps the latex to flow out easily when people make small cuts into the bark.\n\nWhat feature of <i>Hevea brasiliensis</i> does the text say is helpful for the process of making rubber?`,
    options: [
      { id: 'A', text: 'Its latex produces rubber of an especially high quality.' },
      { id: 'B', text: 'Its bark has a unique structure that makes it easy to collect latex.' },
      { id: 'C', text: 'It is able to grow in a wide variety of climates around the world.' },
      { id: 'D', text: 'It is one of only two trees in the Amazon that produce latex.' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because the text explicitly states that "The bark of Hevea brasiliensis is helpful... because it has a unique structure that makes it easy to collect latex."'
  },
  {
    id: 1744,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 11,
    domain: 'Information and Ideas',
    skill: 'Central Ideas and Details',
    questionText: `Conservationists worldwide are working to protect ecosystems from habitat destruction and biodiversity loss, and in many cases, initiatives that rely on natural features or processes can help address such challenges. In response to a rapidly dwindling population of blueback salmon, the Quinault Indian Nation (a tribe in Washington State) partnered with the conservation organization Wild Salmon Center to restore naturally occurring logjams in the Quinault River. The logjams create shady pools where the blueback salmon can rest and spawn, thus promoting blueback population recovery.\n\nWhich choice best states the main idea of the text?`,
    options: [
      { id: 'A', text: 'A partnership between the Quinault Indian Nation and Wild Salmon Center shows the importance of collaborative approaches to preserving biodiversity.' },
      { id: 'B', text: 'Nature-based approaches can be effective ways to achieve conservation goals.' },
      { id: 'C', text: 'As indicated by a recent project, logjams help the blueback salmon thrive and reproduce.' },
      { id: 'D', text: 'Scientists now realize that nature-based conservation methods offer better long-term solutions to environmental issues than methods that are not nature-based do.' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because the passage presents the Quinault River logjam restoration as an example illustrating the broader main idea that nature-based approaches can effectively achieve conservation goals.'
  },
  {
    id: 1745,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 12,
    domain: 'Information and Ideas',
    skill: 'Command of Evidence (Quantitative)',
    passageHtml: `<div class="my-3 overflow-x-auto"><table class="w-full text-xs "><thead><tr class="bg-white"><th class="p-2 border-b border-r text-center font-bold">Highest average surface temperature (Fahrenheit)</th><th class="p-2 border-b text-center font-bold">Percentage of bus stops with shaded shelter</th></tr></thead><tbody><tr class="border-b"><td class="p-2 border-r text-center">90.2°</td><td class="p-2 text-center">15%</td></tr><tr class="border-b"><td class="p-2 border-r text-center">97.7°</td><td class="p-2 text-center">22%</td></tr><tr class="border-b"><td class="p-2 border-r text-center">102.7°</td><td class="p-2 text-center">24%</td></tr><tr class="border-b"><td class="p-2 border-r text-center">111.2°</td><td class="p-2 text-center">28%</td></tr><tr><td class="p-2 border-r text-center">125.6°</td><td class="p-2 text-center">29%</td></tr></tbody></table></div><p class="mt-2">A student is researching a bus system in a large county where surface temperatures vary by area and are hot in the summer. The student claims that all areas of the county should have more bus stops with shaded shelter, noting that the highest percentage of bus stops with shaded shelter for any area is only _______</p>`,
    questionText: `Which choice most effectively uses data from the table to complete the student’s claim?`,
    options: [
      { id: 'A', text: '50%.' },
      { id: 'B', text: '15%.' },
      { id: 'C', text: '90%.' },
      { id: 'D', text: '29%.' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because the highest value in the "Percentage of bus stops with shaded shelter" column in the table is 29% (corresponding to 125.6°F).'
  },
  {
    id: 1746,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 13,
    domain: 'Information and Ideas',
    skill: 'Command of Evidence (Quantitative)',
    passageHtml: `<div class="my-3 overflow-x-auto"><div class="text-center font-bold text-xs mb-2">Total Areas and 2022 Populations of Smallest Arabian Peninsula Countries</div><table class="w-full text-xs "><thead><tr class="bg-white"><th class="p-2 border-b border-r text-center font-bold">Country</th><th class="p-2 border-b border-r text-center font-bold">Total area (square miles)</th><th class="p-2 border-b text-center font-bold">Population</th></tr></thead><tbody><tr class="border-b"><td class="p-2 border-r text-center">Kuwait</td><td class="p-2 border-r text-center">6,880</td><td class="p-2 text-center">4,268,873</td></tr><tr class="border-b"><td class="p-2 border-r text-center">Bahrain</td><td class="p-2 border-r text-center">304</td><td class="p-2 text-center">1,472,233</td></tr><tr><td class="p-2 border-r text-center">Qatar</td><td class="p-2 border-r text-center">4,471</td><td class="p-2 text-center">2,695,122</td></tr></tbody></table></div><p class="mt-2">In terms of area and population, the three smallest Arabian Peninsula countries are Bahrain, Qatar, and Kuwait.</p>`,
    questionText: `According to the table, what is the total area of Bahrain?`,
    options: [
      { id: 'A', text: '4,268,873 square miles' },
      { id: 'B', text: '4,471 square miles' },
      { id: 'C', text: '304 square miles' },
      { id: 'D', text: '6,880 square miles' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because the row for Bahrain lists its total area as 304 square miles.'
  },
  {
    id: 1747,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 14,
    domain: 'Information and Ideas',
    skill: 'Command of Evidence (Textual)',
    questionText: `Janet Echelman is a sculptor and fiber artist. She has installed giant sculptures all over the world. Echelman uses bright and flowing materials, which mimic the wind. <u>However, while her sculptures appear as delicate as a breeze, they are actually very durable.</u>\n\nWhich quotation from an article about Echelman’s sculptures, if true, would most effectively illustrate the underlined claim?`,
    options: [
      { id: 'A', text: '“Echelman uses a special program that makes a 3D model of the sculpture.”' },
      { id: 'B', text: '“The first part of planning a new sculpture is done using paper and pencil, and then a digital program is used to finalize the design.”' },
      { id: 'C', text: '“The materials that Echelman uses to build her sculptures are both flexible and strong.”' },
      { id: 'D', text: '“Each sculpture is designed to reflect local landmarks from the area in which it is eventually installed.”' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because stating that the materials are "both flexible and strong" directly supports the claim that the delicate-looking sculptures are actually durable.'
  },
  {
    id: 1748,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 15,
    domain: 'Information and Ideas',
    skill: 'Command of Evidence (Textual)',
    questionText: `Early Earth is thought to have been characterized by a stagnant lid tectonic regime, in which the upper lithosphere (the outer rocky layer) was essentially immobile and there was no interaction between the lithosphere and the underlying mantle. Researchers investigated the timing of the transition from a stagnant lid regime to a tectonic plate regime, in which the lithosphere is fractured into dynamic plates that in turn allow lithospheric and mantle material to mix. Examining chemical data from lithospheric and mantle-derived rocks ranging from 285 million to 3.8 billion years old, the researchers dated the transition to 3.2 billion years ago.\n\nWhich finding, if true, would most directly support the researchers’ conclusion?`,
    options: [
      { id: 'A', text: 'Among rocks known to be older than 3.2 billion years, significantly more are mantle derived than lithospheric, but the opposite is true for the rocks younger than 3.2 billion years.' },
      { id: 'B', text: 'Mantle-derived rocks older than 3.2 billion years show significantly more compositional diversity than lithospheric rocks older than 3.2 billion years do.' },
      { id: 'C', text: 'There is a positive correlation between the age of lithospheric rocks and their chemical similarity to mantle-derived rocks, and that correlation increases significantly in strength at around 3.2 billion years old.' },
      { id: 'D', text: 'Mantle-derived rocks younger than 3.2 billion years contain some material that is not found in older mantle-derived rocks but is found in older and contemporaneous lithospheric rocks.' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because finding lithospheric material in mantle-derived rocks starting at 3.2 billion years ago proves that lithosphere-mantle mixing began at that time.'
  },
  {
    id: 1749,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 16,
    domain: 'Information and Ideas',
    skill: 'Inference',
    questionText: `The Uto-Aztecan language family is divided into a northern branch, which includes the Shoshone language of present-day Idaho and Utah, and a southern one, whose best-known representative is Nahuatl, the language of the Aztec Empire in Mexico. Lexical similarities across the family, including of botanical terms, confirm descent from a single language spoken millennia ago, and the family’s geographical distribution suggests an origin in what is now the US Southwest. However, vocabulary pertaining to maize isn’t shared between northern and southern branches, despite the crop’s universal cultivation among Uto-Aztecan tribes. Given archaeological evidence that maize originated in Mexico and diffused northward into what became the US Southwest, some linguists reason that _______\n\nWhich choice most logically completes the text?`,
    options: [
      { id: 'A', text: 'northern Uto-Aztecan tribes likely obtained the crop directly from a southern Uto-Aztecan tribe rather than from a non-Uto-Aztecan tribe.' },
      { id: 'B', text: 'variation in maize-related vocabulary within each branch of the Uto-Aztecan family likely reflects regionally specific methods for cultivating the crop.' },
      { id: 'C', text: 'southern Uto-Aztecan tribes likely acquired maize at roughly the same time as northern Uto-Aztecan tribes did, though from different sources.' },
      { id: 'D', text: 'the family’s division into northern and southern branches likely preceded the acquisition of the crop by the Uto-Aztecan tribes.' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because if the languages had already split before maize was adopted, each branch would independently develop its own separate maize vocabulary, explaining why maize terms are not shared.'
  },
  {
    id: 1750,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 17,
    domain: 'Information and Ideas',
    skill: 'Inference',
    questionText: `Data collected by the Mars rover Curiosity at the Gale Crater’s Murray Formation are suggestive of hydrological deposition of sediment in the distant past. To characterize the nature of the depositional environment, Frances Rivera-Hernández et al. analyzed the grain size of Murray Formation sediment, finding that although there are intervals of coarse grains, most of the sediment consists of fine grains that show signs of cracking due to episodic desiccation. Rivera-Hernández et al. concluded that the coarse grains are sandstone, which tends to be deposited by flowing water, whereas the fine grains are mudstone, which is slowly deposited by settling out of suspension in low-flow water, leading the researchers to posit that _______\n\nWhich choice most logically completes the text?`,
    options: [
      { id: 'A', text: 'although the area of the Murray Formation experienced a prolonged period of dryness that prevented a lake from forming, water flowing from a distant source was present.' },
      { id: 'B', text: 'a lake existed at the Murray Formation for a prolonged period, though the lake occasionally experienced drying and there were periods in which one or more streams were present.' },
      { id: 'C', text: 'one or more streams existed at the Murray Formation for an extended period until being replaced by a lake that persisted for only a brief period before permanently drying.' },
      { id: 'D', text: 'a stream-fed lake was present at the Murray Formation for an extended period, and although the streams experienced occasional drying, the lake did not.' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because mostly fine-grain mudstone indicates a persistent low-flow lake, intervals of coarse grains indicate stream flow into the area, and cracking indicates episodic drying.'
  },
  {
    id: 1751,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 18,
    domain: 'Information and Ideas',
    skill: 'Inference',
    questionText: `An analysis by Alain Elayi and colleagues of coins minted in Sidon in the fifth and fourth centuries BCE reveals a change in their composition over time: while a coin from circa 450 BCE contains about 98% silver and 1% copper, a coin from 367 BCE (the end of Ba’alšillem II’s reign) contains 74.2% silver and 24.7% copper, giving it a relatively yellowish appearance that traders would have noticed. Because coins with a silver content below 80% were widely considered unsuitable for trade, Elayi et al. speculate that a crisis in confidence in the currency occurred in Sidon around 367 BCE, which was likely relieved—despite Sidon’s persistent oppressive financial obligations—as a result of Ba’alšillem II’s successor Abd’aštart I’s decision to _______\n\nWhich choice most logically completes the text?`,
    options: [
      { id: 'A', text: 'proclaim that the percentage of silver in coins suitable for trade would be raised to a threshold higher than 80%.' },
      { id: 'B', text: 'keep the amount of silver in Sidonian coins consistent with that in coins minted in 367 BCE but decrease their weight.' },
      { id: 'C', text: 'begin minting heavier coins with a proportion of silver to copper similar to that in coins minted in 367 BCE.' },
      { id: 'D', text: 'restore the silver content of Sidonian coins to at least the 80% threshold necessary for trade.' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because restoring the silver content above the 80% threshold required for trade acceptability would relieve the crisis of confidence caused by debased coins.'
  },
  {
    id: 1752,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 19,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `Nowadays, tug-of-war is usually seen as an informal game one might play at a picnic or in gym class. Surprisingly, the Olympic committee once decided _______ tug-of-war as an official Olympic event! Nations competed in the event at the Olympic Games from 1900 to 1920.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'included' },
      { id: 'B', text: 'including' },
      { id: 'C', text: 'include' },
      { id: 'D', text: 'to include' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because the verb "decided" takes an infinitive complement ("to include").'
  },
  {
    id: 1753,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 20,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `The Globe Theatre in London is a reconstruction of the famed venue where many of Shakespeare’s plays were first performed. In 1613, a prop cannon _______ during a performance and ignited the Globe’s thatched roof. No one was hurt, but in two hours the original Globe was gone.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'malfunctions' },
      { id: 'B', text: 'will malfunction' },
      { id: 'C', text: 'has malfunctioned' },
      { id: 'D', text: 'malfunctioned' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because simple past tense ("malfunctioned") is required for a completed action in a specific historical year ("In 1613").'
  },
  {
    id: 1754,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 21,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `Nigerian American artist Toyin Ojih Odutola uses black-ink pens to create highly detailed drawings of human figures. Her portrait of novelist Zadie _______ is displayed in the National Portrait Gallery in London.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'Smith:' },
      { id: 'B', text: 'Smith—' },
      { id: 'C', text: 'Smith' },
      { id: 'D', text: 'Smith,' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because "Smith" completes the restrictive appositive name "Zadie Smith" directly modifying "novelist" without unnecessary punctuation.'
  },
  {
    id: 1755,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 22,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `When a given industry—water and electricity are two well-known examples—carries high infrastructural start-up costs and other barriers that discourage competition, _______ of just one or two suppliers per municipality. Such industries are known as natural monopolies.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'these often consist' },
      { id: 'B', text: 'they often consist' },
      { id: 'C', text: 'it often consists' },
      { id: 'D', text: 'this often consists' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because the singular subject noun phrase "a given industry" requires the singular pronoun and verb agreement "it often consists".'
  },
  {
    id: 1756,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 23,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `As the fourteenth US librarian of Congress, Carla Hayden has many responsibilities. These include overseeing the Library of Congress’s collections, which boast more than 162 million _______ the US Copyright Office, which registers copyright claims and advises Congress on copyright law; and appointing the US poet laureate.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'items managing' },
      { id: 'B', text: 'items, managing' },
      { id: 'C', text: 'items; managing' },
      { id: 'D', text: 'items. Managing' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because semicolons are required to separate complex list items that themselves contain internal commas ("items; managing... law; and appointing...").'
  },
  {
    id: 1757,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 24,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `Digital artist Jung (Lulu) Chen primarily uses a suite of software tools to create illustrations for children’s books. To manifest the warm and welcoming atmospheres that are a signature of her _______ she occasionally relies on more traditional art techniques, such as painting with watercolors.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'work, though,' },
      { id: 'B', text: 'work, though' },
      { id: 'C', text: 'work; though,' },
      { id: 'D', text: 'work, though;' }
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct because the parenthetical conjunctive adverb "though" modifying the introductory infinitive phrase must be enclosed in commas ("work, though,").'
  },
  {
    id: 1758,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 25,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `Chondrites are stony meteorites that are undifferentiated—that is, their contents have not melted and separated into distinct layers. They are hardly _______ many chondrites experience aqueous alteration as a result of exposure to fluids, as well as fracturing, veining, and localized melting due to collisions with other objects.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'pristine, though' },
      { id: 'B', text: 'pristine, though;' },
      { id: 'C', text: 'pristine; though' },
      { id: 'D', text: 'pristine, though,' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because a semicolon after "though" is required to separate the two independent clauses ("They are hardly pristine, though" and "many chondrites experience...").'
  },
  {
    id: 1759,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 26,
    domain: 'Expression of Ideas',
    skill: 'Form, Structure, and Sense',
    questionText: `That the geographic center of North America lay in the state of North Dakota was conceded by all _______ establishing its precise coordinates proved more divisive.\n\nWhich choice completes the text so that it conforms to the conventions of Standard English?`,
    options: [
      { id: 'A', text: 'involved:' },
      { id: 'B', text: 'involved,' },
      { id: 'C', text: 'involved' },
      { id: 'D', text: 'involved;' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because a semicolon is needed to join two independent clauses ("That the geographic center... was conceded by all involved" and "establishing its precise coordinates proved more divisive") without a coordinating conjunction.'
  },
  {
    id: 1760,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 27,
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    questionText: `Famous for its four-degree tilt, the leaning Garisenda Tower is a popular attraction in Bologna’s city center. However, measurements taken in 2023 showed that the tower was rotating in a concerning way. _______ city officials closed the area around the tower so experts could explore solutions to stabilize the historical twelfth-century structure.\n\nWhich choice completes the text with the most logical transition?`,
    options: [
      { id: 'A', text: 'Similarly,' },
      { id: 'B', text: 'As a result,' },
      { id: 'C', text: 'For example,' },
      { id: 'D', text: 'In comparison,' }
    ],
    correctAnswer: 'B',
    explanation: 'Choice B is correct because "As a result" indicates a direct cause-and-effect relationship between the concerning rotation measurements and closing the area.'
  },
  {
    id: 1761,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 28,
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    questionText: `In 2021, a model developed by astrophysicist Catherine Zucker and her research team revealed that the same supernovas responsible for the creation and ongoing expansion of the Local Bubble—a 14-million-year-old cavity in the Milky Way—are likely responsible for the formation of new stars. _______ this model detailed how the bubble’s expansion trapped interstellar clouds of gas and dust that became stars upon their eventual collapse.\n\nWhich choice completes the text with the most logical transition?`,
    options: [
      { id: 'A', text: 'Hence,' },
      { id: 'B', text: 'However,' },
      { id: 'C', text: 'Admittedly,' },
      { id: 'D', text: 'Specifically,' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because "Specifically" signals that the second sentence provides detailed specifics about how the model works.'
  },
  {
    id: 1762,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 29,
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    questionText: `Following the American Revolutionary War, North American foodways underwent a radical transformation, fueled in large part by spiking consumer demand for certain grains. The cultivation, trade, and transportation of maize and wheat, _______ reconfigured the continent’s existing regional foodways into a globally oriented food system.\n\nWhich choice completes the text with the most logical transition?`,
    options: [
      { id: 'A', text: 'in particular,' },
      { id: 'B', text: 'alternatively,' },
      { id: 'C', text: 'by comparison,' },
      { id: 'D', text: 'second of all,' }
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct because "in particular" highlights maize and wheat as specific examples of "certain grains" mentioned in the previous sentence.'
  },
  {
    id: 1763,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 30,
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    questionText: `When, in 2017, Cambridge University students Lucy Moss and Toby Marlow decided they wanted to develop a musical together, one of their goals was for their female actor friends to have good parts to play. _______ they created the show <i>Six</i>, a retelling of the history of King Henry VIII’s wives in which each of the six queens has a starring role.\n\nWhich choice completes the text with the most logical transition?`,
    options: [
      { id: 'A', text: 'In other words,' },
      { id: 'B', text: 'In summary,' },
      { id: 'C', text: 'For example,' },
      { id: 'D', text: 'To that end,' }
    ],
    correctAnswer: 'D',
    explanation: 'Choice D is correct because "To that end" means "for that purpose," directly linking the action taken (creating Six) with the goal established in the previous sentence.'
  },
  {
    id: 1764,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 31,
    domain: 'Expression of Ideas',
    skill: 'Transitions',
    questionText: `Mountain climbing routes that incorporate metal rungs and cables are known as via ferratas, from the Italian phrase for “iron path.” As climbing these routes has shifted from a mode of travel to a sporting activity, modern via ferratas are rarely designed to simply reach a summit. _______ new routes favor recreation over utility, aiming to provide a challenging climb or showcase dramatic scenery.\n\nWhich choice completes the text with the most logical transition?`,
    options: [
      { id: 'A', text: 'Additionally,' },
      { id: 'B', text: 'On the other hand,' },
      { id: 'C', text: 'More often,' },
      { id: 'D', text: 'Nonetheless,' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because "More often" elaborates on the modern trend described in the preceding sentence.'
  },
  {
    id: 1765,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 32,
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    passageHtml: `<p class="mb-3 font-semibold">While researching a topic, a student has taken the following notes:</p><ul class="list-disc pl-5 space-y-2 mb-3"><li>Samuel Delany is a US writer known for his science fiction.</li><li>Delany’s science fiction novel <i>Babel-17</i> was published in 1966.</li><li>The novel won a Nebula Award in 1967.</li><li>The Nebula Awards are given each year to the best works of science fiction published in the US.</li></ul>`,
    questionText: `The student wants to indicate the title of a novel that won a Nebula Award. Which choice most effectively uses relevant information from the notes to accomplish this goal?`,
    options: [
      { id: 'A', text: '<i>Babel-17</i>, by Samuel Delany, won a Nebula Award in 1967.' },
      { id: 'B', text: 'Samuel Delany published a science fiction novel in 1966.' },
      { id: 'C', text: 'Samuel Delany is an award-winning US writer known for his science fiction.' },
      { id: 'D', text: 'One of Samuel Delany’s novels was among the best works of science fiction published in the US.' }
    ],
    correctAnswer: 'A',
    explanation: 'Choice A is correct because it directly identifies the title of the novel (Babel-17) and states that it won a Nebula Award.'
  },
  {
    id: 1766,
    testId: 'test7',
    moduleKey: 'RW_2',
    section: 'Reading and Writing',
    type: "Reading and Writing",
    moduleNumber: 2,
    questionNumber: 33,
    domain: 'Expression of Ideas',
    skill: 'Rhetorical Synthesis',
    passageHtml: `<p class="mb-3 font-semibold">While researching a topic, a student has taken the following notes:</p><ul class="list-disc pl-5 space-y-2 mb-3"><li>Chiura Obata was a Japanese American artist who lived in California.</li><li><i>Yosemite Falls</i> is a notable painting by Obata.</li><li>It uses a Japanese method of black ink painting called sumi-e.</li><li>This painting was completed in 1930.</li></ul>`,
    questionText: `The student wants to indicate the year <i>Yosemite Falls</i> was completed. Which choice most effectively uses relevant information from the notes to accomplish this goal?`,
    options: [
      { id: 'A', text: 'While living in California, Obata created black ink paintings.' },
      { id: 'B', text: 'Obata, a Japanese American artist, created a notable painting.' },
      { id: 'C', text: '<i>Yosemite Falls</i> was completed in 1930.' },
      { id: 'D', text: 'Obata used a Japanese painting method called sumi-e.' }
    ],
    correctAnswer: 'C',
    explanation: 'Choice C is correct because it explicitly states the painting\'s title and its completion year (1930).'
  }
];
